config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, 
  
    controllers: {
          sessions: 'users/sessions'
        }

    get '/me', to: 'users#show'    
    
    authenticated :user do
      get '/me/add', to: 'users#add_money'
      patch '/me/add', to: 'users#recharge_wallet'
      get '/me/transactions', to: 'users#transactions'
      get '/pokemon/:id/checkout', to: 'pokemons#checkout'
      post '/pokemon/:id/buy', to: 'transactions#register_buy'
      post '/pokemon/:id/sell', to: 'transactions#register_sell'
    end

  resources :pokemon, only: [:index, :show] do
    member do
      get '/pokemon', to: 'pokemons#index'
      get '/pokemon/:id', to: 'pokemons#show'
    end
  end

end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    belongs_to :user
end

app/controllers/pokemon_controller.rb
class PokemonController < ApplicationController
    before_action :set_pokemon, only: [:show, :checkout]
  
    def index
      @pokemon_list = Pokemon.all
      render json: @pokemon_list
    end
  
    def show
      # Show a specific Pokemon
      render json: @pokemon
    end
  
    def checkout
        if @pokemon.user == current_user
          render json: { success: false, message: 'You already own this Pokemon.' }
        else
          # Proceed with the purchase
          # You can redirect to the buy action in TransactionsController or handle the purchase logic directly
        end
    end
  
    private
  
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end
  end
  

app/views/pokemons/checkout.html.erb
<h1>Checkout</h1>

<% if @pokemon.user == current_user %>
  <p>You already own this Pokemon.</p>
<% else %>
  <%= form_for @pokemon, url: checkout_pokemon_path(@pokemon), method: :post do |f| %>
    <!-- You may want to display Pokemon details here for the user -->
    <p>Name: <%= @pokemon.name %></p>
    <p>Price: <%= @pokemon.price %></p>
    <!-- Add any other relevant details -->

    <!-- Add hidden field to specify the action -->
    <%= f.hidden_field :action, value: 'buy' %>

    <!-- Add any additional form fields if needed -->

    <!-- Add form submit button -->
    <%= f.submit "Buy Pokemon" %>
  <% end %>
<% end %>

app/views/pokemons/index.html.erb
<h1>Pokemon List</h1>

<% @pokemon_list.each do |pokemon| %>
  <div>
    <h2><%= pokemon.name %></h2>
    <p>Price: <%= pokemon.price %></p>
    <!-- Add more details as needed -->
    <%= link_to "Show", pokemon_path(pokemon) %>
  </div>
<% end %>

app/views/pokemons/show.html.erb
<h1><%= @pokemon.name %></h1>
<p>Price: <%= @pokemon.price %></p>
<!-- Add more details as needed -->
<!-- For example, you can display weight, height, image, etc. -->

<%= link_to "Back to Pokemon List", pokemons_path %>